# Generated by Django 4.1 on 2025-12-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_gst_order_remove_product_category_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gst_type',
        ),
    ]
