# Generated by Django 4.1 on 2025-12-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_deleted_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
