# Generated by Django 4.1 on 2025-12-14 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0018_contactmessage_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booked_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booked_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
