# Generated by Django 4.1 on 2025-12-14 05:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_order_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
